# Markdownlint configuration
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  # Disable line length for helm-docs generated tables and code blocks
  line_length: 120
  # Number of characters for headings
  heading_line_length: 80
  # Number of characters for code blocks
  code_block_line_length: 120
  # Include code blocks
  code_blocks: false
  # Include tables
  tables: false

# MD033/no-inline-html - Inline HTML
MD033:
  # Allow specific HTML elements (needed for helm-docs)
  allowed_elements:
    - a
    - br
    - details
    - summary

# MD041/first-line-heading - First line in file should be a top level heading
MD041: false
