# Markdownlint configuration
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# MD004/ul-style - Unordered list style
# Disabled because helm-docs may use different list styles
MD004: false

# MD013/line-length - Line length
# Disabled because helm-docs generates long lines in tables
MD013: false

# MD032/blanks-around-lists - Lists should be surrounded by blank lines
# Disabled because helm-docs formatting varies
MD032: false

# MD034/no-bare-urls - Bare URL used
# Disabled because helm-docs generates bare URLs in documentation
MD034: false

# MD033/no-inline-html - Inline HTML
MD033:
  # Allow specific HTML elements (needed for helm-docs)
  allowed_elements:
    - a
    - br
    - details
    - summary

# MD041/first-line-heading - First line in file should be a top level heading
MD041: false
