{{- if not .Values.static }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vipalived.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vipalived.labels" . | nindent 4 }}
data:
  keepalived.conf: |
    {{- include "vipalived.keepalivedConfig" . | nindent 4 }}
{{- end }}
