apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system-upgrade-controller-drainer
  labels:
    {{- include "system-upgrade-controller.labels" . | nindent 4 }}
rules:
  # Needed to evict pods
  - apiGroups:
      - ""
    resources:
      - "pods/eviction"
    verbs:
      - "create"
  # Needed to list/delete pods by Node
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "get"
      - "list"
      - "delete"
  # Needed to cordon Nodes
  - apiGroups:
      - ""
    resources:
      - "nodes"
    verbs:
      - "get"
      - "patch"
  # Needed to determine Pod owners
  - apiGroups:
      - "apps"
    resources:
      - "statefulsets"
      - "daemonsets"
      - "replicasets"
    verbs:
      - "get"
      - "list"
