apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-upgrade
  labels:
    {{- include "system-upgrade-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system-upgrade-controller
subjects:
- kind: ServiceAccount
  name: {{ include "system-upgrade-controller.serviceAccountName" . }}
  namespace: {{ include "system-upgrade-controller.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-upgrade-drainer
  labels:
    {{- include "system-upgrade-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system-upgrade-controller-drainer
subjects:
- kind: ServiceAccount
  name: {{ include "system-upgrade-controller.serviceAccountName" . }}
  namespace: {{ include "system-upgrade-controller.namespace" . }}
