apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system-upgrade
  namespace: {{ include "system-upgrade-controller.namespace" . }}
  labels:
    {{- include "system-upgrade-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system-upgrade-controller
subjects:
- kind: ServiceAccount
  name: {{ include "system-upgrade-controller.serviceAccountName" . }}
  namespace: {{ include "system-upgrade-controller.namespace" . }}
