name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: dropdown
    id: chart
    attributes:
      label: Chart
      description: Which chart is affected?
      options:
        - cloudflare-tunnel
        - system-upgrade-controller
        - transmission
        - vipalived
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Chart Version
      description: What version of the chart are you using?
      placeholder: "e.g., 0.12.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: What actually happens?

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Install chart with ...
        2. Configure ...
        3. See error ...

  - type: textarea
    id: values
    attributes:
      label: Values File
      description: Relevant parts of your values.yaml (remove secrets!)
      render: yaml

  - type: input
    id: kubernetes-version
    attributes:
      label: Kubernetes Version
      description: Output of `kubectl version --short`
      placeholder: "e.g., v1.28.0"

  - type: input
    id: helm-version
    attributes:
      label: Helm Version
      description: Output of `helm version --short`
      placeholder: "e.g., v3.13.0"

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, logs, or screenshots
