apiVersion: v2
name: me-site
description: A Helm chart for the Me-Site application
type: application
version: 0.6.0
appVersion: 1.0.0
maintainers:
  - name: lexfrei
    email: f@lex.la
    url: https://github.com/lexfrei
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: "automountServiceAccountToken value to control API token automounting"
    - kind: changed
      description: "Do not automount the ServiceAccount API token by default, as me-site does not use the Kubernetes API"
kubeVersion: '>=1.19.0-0'
