apiVersion: v1
kind: Service
metadata:
  name: me-site
  labels:
    app: me-site
spec:
  ports:
    - port: {{ .Values.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
    app: me-site
