{{- if and (ne .Values.database.type "sqlite") (not .Values.database.existingSecret) .Values.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spoolman.fullname" . }}
  labels:
    {{- include "spoolman.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc | quote }}
{{- end }}
